# Generated by Django 5.0.14 on 2026-05-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflows.workflowstep')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['workflow_run', 'step__order'],
                'unique_together': {('workflow_run', 'step')},
            },
        ),
    ]
