# Generated by Django 5.0.14 on 2026-05-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowsteprun'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_back', 'Sent Back'), ('escalated', 'Escalated')], max_length=20)),
                ('decided_by', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('step_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workflows.workflowsteprun')),
            ],
        ),
    ]
